# Generated by Django 5.2.14 on 2026-07-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=200, null=True, verbose_name="Email"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Téléphone")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("cni", "Carte Nationale d'Identité"),
                            ("passport", "Passeport"),
                            ("permis", "Permis de Conduire"),
                            ("carte_sejour", "Carte de Séjour"),
                            ("autre", "Autre"),
                        ],
                        default="cni",
                        max_length=20,
                        verbose_name="Type de pièce",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro de pièce"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "is_regular",
                    models.BooleanField(default=True, verbose_name="Client régulier"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bénéficiaire de retrait",
                "verbose_name_plural": "Bénéficiaires de retraits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Nom du bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Téléphone du bénéficiaire",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="finance.withdrawalrecipient",
                verbose_name="Bénéficiaire du retrait",
            ),
        ),
    ]
