# Generated by Django 5.2.14 on 2026-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_withdrawalrecipient_transaction_recipient_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "ENTRÉE"),
                    ("transfer_to_agent", "Transfert vers Agent"),
                    ("withdrawal", "SORTIE"),
                ],
                max_length=20,
            ),
        ),
    ]
