# Generated by Django 5.2.14 on 2026-09-28 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={
                "verbose_name": "Partenaire",
                "verbose_name_plural": "Partenaires",
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de suppression"
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Supprimé"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_reversed",
            field=models.BooleanField(default=False, verbose_name="Annulée"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversal_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversed_transaction",
                to="finance.transaction",
                verbose_name="Transaction d'annulation",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reversed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'annulation"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "ENTRÉE"),
                    ("transfer_to_agent", "Transfert vers Agent"),
                    ("withdrawal", "SORTIE"),
                    ("transfer_between_agents", "Transfert entre Agents"),
                    ("partner_deletion_reversal", "Annulation suppression partenaire"),
                ],
                max_length=30,
            ),
        ),
    ]
