# Generated by Django 5.2.14 on 2026-09-28 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_partner_options_partner_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_account_label_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="from_account_type_snapshot",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_account_label_snapshot",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="to_account_type_snapshot",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="from_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outgoing_transactions",
                to="finance.account",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="to_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incoming_transactions",
                to="finance.account",
            ),
        ),
    ]
