# Generated by Django 5.2.14 on 2026-10-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "ENTRÉE"),
                    ("transfer_to_agent", "Transfert vers Agent"),
                    ("withdrawal", "SORTIE"),
                    ("transfer_between_agents", "Transfert entre Agents"),
                    ("reversal", "Annulation de transaction"),
                    ("partner_deletion_reversal", "Annulation suppression partenaire"),
                ],
                max_length=30,
            ),
        ),
    ]
