# Generated by Django 5.2.14 on 2026-07-18 14:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("stats", "Statistiques"),
                            ("chart", "Graphique"),
                            ("table", "Tableau"),
                            ("map", "Carte"),
                            ("activity", "Activité récente"),
                            ("alert", "Alertes"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Configuration du widget"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False, help_text="Widget système non supprimable"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
            },
        ),
        migrations.CreateModel(
            name="DashboardAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("danger", "Critique"),
                            ("success", "Succès"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte",
                "verbose_name_plural": "Alertes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total_balance", "Solde total"),
                            ("total_transactions", "Total transactions"),
                            ("active_agents", "Agents actifs"),
                            ("total_partners", "Total partenaires"),
                            ("revenue", "Revenus"),
                            ("withdrawal_volume", "Volume retraits"),
                            ("deposit_volume", "Volume dépôts"),
                            ("custom", "Personnalisé"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=20
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Métrique",
                "verbose_name_plural": "Métriques",
                "ordering": ["-date"],
                "unique_together": {("metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="DashboardPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widgets_order",
                    models.JSONField(
                        blank=True, default=list, help_text="Ordre des widgets"
                    ),
                ),
                (
                    "hidden_widgets",
                    models.JSONField(
                        blank=True, default=list, help_text="Widgets masqués"
                    ),
                ),
                (
                    "date_range",
                    models.CharField(
                        default="last_30_days",
                        help_text="Plage de dates par défaut",
                        max_length=50,
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=30,
                        help_text="Intervalle de rafraîchissement en secondes",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Clair"), ("dark", "Sombre")],
                        default="light",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de tableau de bord",
                "verbose_name_plural": "Préférences de tableau de bord",
            },
        ),
    ]
